import os
from pathlib import Path
import pandas as pd
import numpy as np
import streamlit as st
import plotly.express as px
import plotly.graph_objects as go
import joblib

# Paths
PROJECT_ROOT = Path(__file__).resolve().parent
TRAIN_CSV_PEKERJA = PROJECT_ROOT / "Dataset" / "DatasetPekerja.csv"
TRAIN_CSV_DEFAULT = PROJECT_ROOT / "Dataset" / "train.csv"
TRAIN_CSV = TRAIN_CSV_PEKERJA if TRAIN_CSV_PEKERJA.exists() else TRAIN_CSV_DEFAULT
MODEL_DIR = PROJECT_ROOT / "model"

# Set Streamlit Page Configuration
st.set_page_config(
    page_title="Salary Classifier Dashboard",
    page_icon="💰",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom Styling (Rich Aesthetic - Dark Mode Theme & Harmonious Color Palette)
st.markdown("""
<style>
    /* Google Fonts */
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Outfit', sans-serif;
    }
    
    /* Title Styling with Gradient */
    .title-gradient {
        background: linear-gradient(135deg, #FF6B6B 0%, #4D96FF 100%);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        font-weight: 700;
        font-size: 2.8rem;
        margin-bottom: 0.2rem;
    }
    
    .subtitle-text {
        color: #A5F3FC;
        font-size: 1.1rem;
        font-weight: 400;
        margin-bottom: 2rem;
    }
    
    /* Custom Card Styling */
    .metric-card {
        background-color: #1E293B;
        border-radius: 12px;
        padding: 1.5rem;
        border: 1px solid #334155;
        box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
        text-align: center;
        transition: transform 0.2s;
    }
    
    .metric-card:hover {
        transform: translateY(-2px);
        border-color: #4D96FF;
    }
    
    .metric-card-title {
        color: #94A3B8;
        font-size: 0.9rem;
        font-weight: 600;
        text-transform: uppercase;
        margin-bottom: 0.5rem;
    }
    
    .metric-card-value {
        color: #F8FAFC;
        font-size: 2rem;
        font-weight: 700;
    }
</style>
""", unsafe_allow_html=True)


# Load dataset helper with caching
@st.cache_data
def load_raw_data() -> pd.DataFrame:
    """Load raw train.csv and do basic cleaning of columns for EDA."""
    if not TRAIN_CSV.exists():
        st.error(f"Dataset tidak ditemukan di path: {TRAIN_CSV}. Pastikan dataset diletakkan dengan benar.")
        return pd.DataFrame()
    df = pd.read_csv(TRAIN_CSV, sep=";")
    return df


@st.cache_resource
def load_model_artifacts():
    """Load the trained model and preprocessing artifact from disk."""
    model_path = MODEL_DIR / "rf_tuned_main.pkl"
    preprocessor_path = MODEL_DIR / "preprocessor.pkl"

    if not model_path.exists() or not preprocessor_path.exists():
        st.error("Artifact model belum tersedia. Jalankan train_model.py terlebih dahulu.")
        return None, None

    model = joblib.load(model_path)
    artifact = joblib.load(preprocessor_path)
    return model, artifact


@st.cache_data
def load_metrics_artifact():
    """Load evaluation metrics generated by train_model.py."""
    metrics_path = MODEL_DIR / "metrics.pkl"
    if not metrics_path.exists():
        return {}
    return joblib.load(metrics_path)


MODEL_FEATURES = [
    "Umur",
    "Kelas Pekerja",
    "Pendidikan",
    "Jmlh Tahun Pendidikan",
    "Status Perkawinan",
    "Pekerjaan",
    "Jenis Kelamin",
    "Keuntungan Kapital",
    "Kerugian Capital",
    "Jam per Minggu",
]


def build_confusion_matrix_figure(cm, title: str):
    """Create a Plotly heatmap for a confusion matrix."""
    cm_array = np.array(cm)
    fig = go.Figure(
        data=go.Heatmap(
            z=cm_array,
            x=["<=7jt", ">7jt"],
            y=["<=7jt", ">7jt"],
            colorscale="Blues",
            text=cm_array.astype(str),
            texttemplate="%{text}",
            hovertemplate="Aktual: %{y}<br>Prediksi: %{x}<br>Jumlah: %{z}<extra></extra>",
        )
    )
    fig.update_layout(
        title=title,
        template="plotly_dark",
        xaxis_title="Prediksi",
        yaxis_title="Aktual",
        margin=dict(t=40, l=20, r=20, b=20),
    )
    return fig


def predict_salary(model, artifact, user_input: dict) -> tuple[str, float]:
    """Apply preprocessing via full pipeline model and return the predicted class label and probability."""
    input_df = pd.DataFrame([user_input], columns=MODEL_FEATURES)
    input_df = input_df[MODEL_FEATURES]

    # Convert to numeric
    for col in ["Umur", "Jmlh Tahun Pendidikan", "Keuntungan Kapital", "Kerugian Capital", "Jam per Minggu"]:
        input_df[col] = pd.to_numeric(input_df[col], errors="coerce")

    # Model is a full Pipeline with preprocessing, so pass raw data directly
    probability = float(model.predict_proba(input_df)[:, 1][0])
    label = ">7jt" if probability >= 0.5 else "<=7jt"
    return label, probability


def main() -> None:
    # Sidebar
    st.sidebar.image("https://cdn-icons-png.flaticon.com/512/3135/3135706.png", width=80)
    st.sidebar.markdown("### Salary Predictor & EDA Portal")
    st.sidebar.info("Gunakan navigasi tab di sebelah kanan untuk menjelajahi aplikasi.")
    
    # App Header
    st.markdown('<div class="title-gradient">💰 Salary Classifier Dashboard</div>', unsafe_allow_html=True)
    st.markdown('<div class="subtitle-text">Prediksi dan Analisis Kategori Gaji Pekerja berbasis Machine Learning (Random Forest dengan Pendekatan Class Weighting)</div>', unsafe_allow_html=True)

    # 5 Tabs
    tabs = st.tabs([
        "📊 Dashboard EDA",
        "🔮 Model Demo",
        "🎯 Evaluasi Model",
        "💡 Interpretasi Hasil",
        "📖 Dokumentasi"
    ])
    
    # Load Data
    df_raw = load_raw_data()
    if df_raw.empty:
        return

    # ==================== TAB 1: DASHBOARD EDA ====================
    with tabs[0]:
        st.header("Analisis Data Eksploratif (EDA)")
        st.markdown("Tab ini menyajikan wawasan mendalam tentang struktur data dan pengaruh fitur-fitur pekerja terhadap kategori gaji.")
        
        # 1. Summary Statistics & Metrics Cards
        st.subheader("Ringkasan Statistik & Dataset")
        total_rows = len(df_raw)
        missing_cells = df_raw.isin(["?"]).sum().sum()
        duplicated_rows = df_raw.drop(columns=["id"]).duplicated().sum()
        
        # Metric Grid
        m_col1, m_col2, m_col3 = st.columns(3)
        with m_col1:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-card-title">Jumlah Baris Data</div>
                <div class="metric-card-value">{total_rows:,}</div>
            </div>
            """, unsafe_allow_html=True)
        with m_col2:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-card-title">Missing Values ('?')</div>
                <div class="metric-card-value">{missing_cells:,}</div>
            </div>
            """, unsafe_allow_html=True)
        with m_col3:
            st.markdown(f"""
            <div class="metric-card">
                <div class="metric-card-title">Baris Duplikat (Tanpa ID)</div>
                <div class="metric-card-value">{duplicated_rows:,}</div>
            </div>
            """, unsafe_allow_html=True)
        
        st.write("") # Spacer
        
        # Descriptive Stats Table & Missing Values Table
        stat_col1, stat_col2 = st.columns([2, 1])
        with stat_col1:
            st.markdown("##### Statistik Deskriptif Fitur Numerik")
            st.dataframe(df_raw.describe().round(2), use_container_width=True)
        with stat_col2:
            st.markdown("##### Nilai Hilang per Kolom")
            # Replace "?" to nan to count missing values
            df_missing = df_raw.replace("?", np.nan)
            missing_series = df_missing.isnull().sum()
            missing_df = pd.DataFrame({
                "Kolom": missing_series.index,
                "Missing Values": missing_series.values,
                "Persentase": (missing_series.values / len(df_raw) * 100).round(2)
            })
            st.dataframe(missing_df[missing_df["Missing Values"] > 0].reset_index(drop=True), use_container_width=True)
            
        st.divider()
        
        # 2. Target Variable Distribution (Plotly Bar & Pie)
        st.subheader("Distribusi Kelas Target (Gaji)")
        dist_col1, dist_col2 = st.columns(2)
        
        target_counts = df_raw["Gaji"].value_counts().reset_index()
        target_counts.columns = ["Gaji", "Jumlah"]
        
        with dist_col1:
            fig_bar = px.bar(
                target_counts, 
                x="Gaji", 
                y="Jumlah", 
                color="Gaji",
                color_discrete_map={"<=7jt": "#4D96FF", ">7jt": "#FF6B6B"},
                text_auto=True,
                title="Jumlah Pekerja per Kategori Gaji"
            )
            fig_bar.update_layout(showlegend=False, template="plotly_dark")
            st.plotly_chart(fig_bar, use_container_width=True)
            
        with dist_col2:
            fig_pie = px.pie(
                target_counts, 
                names="Gaji", 
                values="Jumlah",
                color="Gaji",
                color_discrete_map={"<=7jt": "#4D96FF", ">7jt": "#FF6B6B"},
                hole=0.4,
                title="Proporsi Kategori Gaji"
            )
            fig_pie.update_layout(template="plotly_dark")
            st.plotly_chart(fig_pie, use_container_width=True)
            
        st.divider()
        
        # 3. Dynamic Feature Distribution vs Gaji (Interactive Boxplot / Bar Chart)
        st.subheader("Analisis Relasi Fitur terhadap Kategori Gaji")
        features_to_analyze = [
            "Umur", 
            "Jam per Minggu", 
            "Jmlh Tahun Pendidikan", 
            "Status Perkawinan", 
            "Jenis Kelamin", 
            "Pendidikan"
        ]
        
        selected_feature = st.selectbox(
            "Pilih fitur yang ingin dianalisis hubungannya dengan Gaji:",
            features_to_analyze
        )
        
        # Determine if numeric or categorical
        is_numeric = df_raw[selected_feature].dtype in [np.int64, np.float64]
        
        if is_numeric:
            fig_relation = px.box(
                df_raw,
                x="Gaji",
                y=selected_feature,
                color="Gaji",
                color_discrete_map={"<=7jt": "#4D96FF", ">7jt": "#FF6B6B"},
                points="outliers",
                title=f"Distribusi {selected_feature} berdasarkan Kategori Gaji"
            )
            fig_relation.update_layout(template="plotly_dark")
            st.plotly_chart(fig_relation, use_container_width=True)
        else:
            # Categorical - Plot a stacked/grouped proportion bar chart
            # First, group by selected feature and Gaji
            df_group = df_raw[df_raw[selected_feature] != "?"].groupby([selected_feature, "Gaji"]).size().reset_index(name="Count")
            
            # Calculate proportion within each category of the selected feature
            df_totals = df_group.groupby(selected_feature)["Count"].transform("sum")
            df_group["Proporsi"] = df_group["Count"] / df_totals
            
            fig_relation = px.bar(
                df_group,
                x=selected_feature,
                y="Proporsi",
                color="Gaji",
                color_discrete_map={"<=7jt": "#4D96FF", ">7jt": "#FF6B6B"},
                barmode="group",
                title=f"Proporsi Kategori Gaji berdasarkan {selected_feature}",
                labels={"Proporsi": "Proporsi Pekerja"}
            )
            fig_relation.update_layout(yaxis_tickformat=".0%", template="plotly_dark")
            st.plotly_chart(fig_relation, use_container_width=True)

    # ==================== TAB 2: MODEL DEMO ====================
    with tabs[1]:
        st.header("Demo Prediksi Kategori Gaji")
        st.markdown("Masukkan profil pekerja untuk melihat prediksi kategori gaji berdasarkan model Random Forest dengan Pendekatan Class Weighting yang sudah dilatih.")

        model, artifact = load_model_artifacts()
        if model is None or artifact is None:
            st.stop()

        categorical_options = {
            "Kelas Pekerja": sorted([str(v) for v in df_raw["Kelas Pekerja"].dropna().astype(str).unique() if str(v) != "?"]),
            "Pendidikan": sorted([str(v) for v in df_raw["Pendidikan"].dropna().astype(str).unique() if str(v) != "?"]),
            "Status Perkawinan": sorted([str(v) for v in df_raw["Status Perkawinan"].dropna().astype(str).unique() if str(v) != "?"]),
            "Pekerjaan": sorted([str(v) for v in df_raw["Pekerjaan"].dropna().astype(str).unique() if str(v) != "?"]),
            "Jenis Kelamin": sorted([str(v) for v in df_raw["Jenis Kelamin"].dropna().astype(str).unique() if str(v) != "?"]),
        }

        with st.form("prediction_form"):
            col1, col2 = st.columns(2)
            with col1:
                umur = st.number_input("Umur", min_value=0, max_value=100, value=35, step=1)
                kelas_pekerja = st.selectbox("Kelas Pekerja", options=categorical_options["Kelas Pekerja"])
                pendidikan = st.selectbox("Pendidikan", options=categorical_options["Pendidikan"])
                jmlh_tahun_pendidikan = st.number_input("Jmlh Tahun Pendidikan", min_value=0, max_value=24, value=12, step=1)
                status_perkawinan = st.selectbox("Status Perkawinan", options=categorical_options["Status Perkawinan"])
            with col2:
                pekerjaan = st.selectbox("Pekerjaan", options=categorical_options["Pekerjaan"])
                jenis_kelamin = st.selectbox("Jenis Kelamin", options=categorical_options["Jenis Kelamin"])
                keuntungan_kapital = st.number_input("Keuntungan Kapital", min_value=0, value=0, step=1, format="%.0f")
                kerugian_capital = st.number_input("Kerugian Capital", min_value=0, value=0, step=1, format="%.0f")
                jam_per_minggu = st.number_input("Jam per Minggu", min_value=0, max_value=100, value=40, step=1)

            submitted = st.form_submit_button("Prediksi")

        if submitted:
            user_input = {
                "Umur": umur,
                "Kelas Pekerja": kelas_pekerja,
                "Pendidikan": pendidikan,
                "Jmlh Tahun Pendidikan": jmlh_tahun_pendidikan,
                "Status Perkawinan": status_perkawinan,
                "Pekerjaan": pekerjaan,
                "Jenis Kelamin": jenis_kelamin,
                "Keuntungan Kapital": keuntungan_kapital,
                "Kerugian Capital": kerugian_capital,
                "Jam per Minggu": jam_per_minggu,
            }
            prediction_label, probability = predict_salary(model, artifact, user_input)

            st.success(f"Prediksi kelas gaji: {prediction_label}")
            col_metric1, col_metric2 = st.columns(2)
            with col_metric1:
                st.metric("Kategori Prediksi", prediction_label)
            with col_metric2:
                st.metric("Probabilitas >7jt", f"{probability:.1%}")

            st.progress(probability)
            st.caption("Nilai probabilitas mendekati 1 menunjukkan kecenderungan kelas >7jt, sedangkan mendekati 0 menunjukkan <=7jt.")

    # ==================== TAB 3: EVALUASI MODEL ====================
    with tabs[2]:
        st.header("Evaluasi Kinerja Model")
        st.markdown("Perbandingan metrik evaluasi dan visualisasi performa lima model yang telah dilatih.")

        metrics = load_metrics_artifact()
        if not metrics:
            st.warning("File metrics belum tersedia. Jalankan train_model.py terlebih dahulu.")
            st.stop()

        # Display comparison table (already pre-built with all 5 models)
        comparison_table = metrics.get("comparison_table", [])
        if comparison_table:
            comparison_df = pd.DataFrame(comparison_table)
            st.dataframe(comparison_df, use_container_width=True)
        else:
            st.warning("Comparison table tidak tersedia.")
            st.stop()

        # Project Success Metrics Info Box
        st.info(
            "📊 **Metrik Kesuksesan Proyek:**\n\n"
            "Target utama penelitian ini adalah mencapai:\n"
            "- **Recall kelas >7jt > 0.75**: Model harus mampu mengidentifikasi setidaknya 75% dari pekerja berpenghasilan >7jt\n"
            "- **ROC-AUC > 0.85**: Model harus memiliki discriminative ability yang baik\n\n"
            f"**Status Model Utama (RF Tuned):**\n"
            f"- Recall >7jt: {comparison_df[comparison_df['Model'] == 'RF Tuned']['Recall'].values[0]:.4f} "
            f"({'✓ TERCAPAI' if comparison_df[comparison_df['Model'] == 'RF Tuned']['Recall'].values[0] > 0.75 else '✗ Belum tercapai'})\n"
            f"- ROC-AUC: {comparison_df[comparison_df['Model'] == 'RF Tuned']['ROC-AUC'].values[0]:.4f} "
            f"({'✓ TERCAPAI' if comparison_df[comparison_df['Model'] == 'RF Tuned']['ROC-AUC'].values[0] > 0.85 else '✗ Belum tercapai'})"
        )

        st.subheader("Confusion Matrix (Semua Model)")
        cm_col1, cm_col2, cm_col3 = st.columns(3)
        with cm_col1:
            st.plotly_chart(build_confusion_matrix_figure(metrics["baseline"]["confusion_matrix"], "RF Baseline"), use_container_width=True)
        with cm_col2:
            st.plotly_chart(build_confusion_matrix_figure(metrics["tuned"]["confusion_matrix"], "RF Tuned (Model Utama)"), use_container_width=True)
        with cm_col3:
            st.plotly_chart(build_confusion_matrix_figure(metrics["logreg"]["confusion_matrix"], "Logistic Regression"), use_container_width=True)
        
        st.subheader("Perbandingan Metrik Evaluasi Lima Model")
        # Melt the comparison dataframe for plotting
        comparison_melt = comparison_df.melt(id_vars=["Model"], value_vars=["Accuracy", "Precision", "Recall", "F1-Score", "ROC-AUC"], var_name="Metric", value_name="Value")
        
        fig_comparison = px.bar(
            comparison_melt,
            x="Model",
            y="Value",
            color="Metric",
            barmode="group",
            title="Perbandingan Metrik Evaluasi Lima Model",
            color_discrete_map={
                "Accuracy": "#4D96FF",
                "Precision": "#FF6B6B", 
                "Recall": "#6BCB77", 
                "F1-Score": "#FFD93D", 
                "ROC-AUC": "#9B59B6"
            },
            text_auto=".3f",
            height=500
        )
        fig_comparison.update_layout(template="plotly_dark")
        st.plotly_chart(fig_comparison, use_container_width=True)

        st.subheader("Cross Validation F1-score per Fold (Model Utama)")
        cv_scores = metrics["tuned"].get("cv_scores_f1", [])
        if cv_scores:
            cv_df = pd.DataFrame({
                "Fold": [f"Fold {idx + 1}" for idx in range(len(cv_scores))],
                "F1 Score": cv_scores,
            })
            fig_cv = px.bar(
                cv_df,
                x="Fold",
                y="F1 Score",
                text="F1 Score",
                title="F1-score per Fold pada Stratified 5-Fold CV",
                color="F1 Score",
                color_continuous_scale="Blues",
            )
            fig_cv.update_layout(template="plotly_dark")
            st.plotly_chart(fig_cv, use_container_width=True)
        else:
            st.info("Tidak ada data cross-validation yang tersedia.")

        st.subheader("Learning Curve (Model Utama)")
        curve = metrics["tuned"].get("learning_curve", {})
        if curve:
            fig_curve = go.Figure()
            fig_curve.add_trace(
                go.Scatter(
                    x=curve.get("train_sizes", []),
                    y=curve.get("train_scores_mean", []),
                    mode="lines+markers",
                    name="Training F1",
                    line=dict(color="#4D96FF"),
                )
            )
            fig_curve.add_trace(
                go.Scatter(
                    x=curve.get("train_sizes", []),
                    y=curve.get("val_scores_mean", []),
                    mode="lines+markers",
                    name="Validation F1",
                    line=dict(color="#FF6B6B"),
                )
            )
            fig_curve.update_layout(
                title="Learning Curve Model Utama",
                template="plotly_dark",
                xaxis_title="Jumlah Sampel Latih",
                yaxis_title="Rata-rata F1-score",
                margin=dict(t=40, l=20, r=20, b=20),
            )
            st.plotly_chart(fig_curve, use_container_width=True)
        else:
            st.info("Tidak ada data learning curve yang tersedia.")

    # ==================== TAB 4: INTERPRETASI HASIL ====================
    with tabs[3]:
        st.header("Interpretasi & Insight Model")
        st.markdown("Visualisasi fitur yang paling memengaruhi prediksi model utama menggunakan tiga teknik interpretasi berbeda, beserta insight bisnis.")

        metrics = load_metrics_artifact()
        if not metrics:
            st.warning("File metrics belum tersedia. Jalankan train_model.py terlebih dahulu.")
            st.stop()

        tuned_metrics = metrics.get("tuned", {})
        
        # ========== Section 1: Feature Importance (Built-in) ==========
        st.subheader("1. Feature Importance (Mean Decrease in Impurity)")
        st.markdown("Metrik bawaan Random Forest berdasarkan peningkatan kemurnian (impurity) saat fitur dipilih dalam split tree.")
        
        feature_importance = tuned_metrics.get("feature_importances", {})
        if feature_importance:
            names = feature_importance.get("names", [])
            importances = feature_importance.get("importances", [])
            if names and importances:
                importance_df = pd.DataFrame({
                    "Fitur": names,
                    "Pentingnya": importances,
                }).sort_values("Pentingnya", ascending=False).head(15)

                fig_importance = px.bar(
                    importance_df,
                    x="Pentingnya",
                    y="Fitur",
                    orientation="h",
                    text="Pentingnya",
                    color="Pentingnya",
                    color_continuous_scale="Blues",
                    title="Top 15 Fitur Berdasarkan Feature Importance"
                )
                fig_importance.update_layout(template="plotly_dark", yaxis={'autorange':'reversed'}, height=500)
                st.plotly_chart(fig_importance, use_container_width=True)
            else:
                st.info("Tidak tersedia data feature importance.")
        else:
            st.info("Tidak tersedia data feature importance.")

        # ========== Section 2: Permutation Importance ==========
        st.subheader("2. Permutation Importance (Model-Agnostic)")
        st.markdown("Metrik ini mengukur penurunan performa ketika nilai fitur di-shuffle secara acak, menunjukkan kontribusi praktis setiap fitur.")
        
        perm_importance = tuned_metrics.get("permutation_importance", {})
        if perm_importance:
            perm_names = perm_importance.get("names", [])
            perm_means = perm_importance.get("importances_mean", [])
            perm_stds = perm_importance.get("importances_std", [])
            if perm_names and perm_means:
                perm_df = pd.DataFrame({
                    "Fitur": perm_names,
                    "Pentingnya": perm_means,
                    "Std Dev": perm_stds,
                }).sort_values("Pentingnya", ascending=False).head(15)

                fig_perm = px.bar(
                    perm_df,
                    x="Pentingnya",
                    y="Fitur",
                    orientation="h",
                    text="Pentingnya",
                    error_x="Std Dev",
                    color="Pentingnya",
                    color_continuous_scale="Oranges",
                    title="Top 15 Fitur Berdasarkan Permutation Importance"
                )
                fig_perm.update_layout(template="plotly_dark", yaxis={'autorange':'reversed'}, height=500)
                st.plotly_chart(fig_perm, use_container_width=True)
            else:
                st.info("Tidak tersedia data permutation importance.")
        else:
            st.info("Tidak tersedia data permutation importance.")

        # ========== Observation: Feature Importance vs Permutation Importance ==========
        st.info(
            "🔍 **Observasi Penting:** Perhatikan bahwa **Jenis Kelamin** menunjukkan importansi tinggi pada "
            "feature importance bawaan, namun hampir tidak berkontribusi pada permutation importance. Ini adalah contoh klasik "
            "**bias Mean Decrease in Impurity** terhadap fitur kategorikal dengan banyak dummy variable. "
            "Feature importance bawaan cenderung overestimate pentingnya fitur dengan banyak kategori, sementara "
            "permutation importance memberikan gambaran yang lebih akurat tentang kontribusi praktis fitur tersebut."
        )

        # ========== Section 3: SHAP Summary Plot ==========
        st.subheader("3. SHAP Summary Plot (SHapley Additive exPlanations)")
        st.markdown("Teknik interpretasi berbasis game theory yang menunjukkan dampak setiap fitur terhadap prediksi model untuk seluruh dataset uji (subsample 300 baris).")
        
        shap_image_path = MODEL_DIR / "shap_summary.png"
        if shap_image_path.exists():
            st.image(str(shap_image_path), caption="SHAP Summary Plot: Distribusi dampak fitur terhadap prediksi kelas >7jt", use_column_width=True)
        else:
            st.warning("File SHAP summary plot belum tersedia.")

        # ========== Insight Bisnis ==========
        st.subheader("Insight Bisnis dari Ketiga Teknik Interpretasi")
        st.markdown("""
        **Konsistensi Antar Teknik:**
        
        Ketiga teknik interpretasi (feature importance bawaan, permutation importance, dan SHAP) secara konsisten mengidentifikasi 
        **Status Perkawinan**, **Jmlh Tahun Pendidikan**, dan **Umur** sebagai fitur-fitur yang paling berpengaruh terhadap prediksi kategori gaji:
        
        - **Status Perkawinan**: Mencerminkan stabilitas keluarga dan potensi dual income, yang berkorelasi kuat dengan tingkat gaji.
        - **Jmlh Tahun Pendidikan**: Semakin tinggi durasi pendidikan, semakin besar peluang untuk meniti karir yang menguntungkan.
        - **Umur**: Berkaitan dengan pengalaman kerja dan matang dalam karir.
        
        **Implikasi Praktis:**
        
        - Fitur demografis dan sosial-ekonomi (status perkawinan, pendidikan, usia, pekerjaan) adalah determinan utama gaji di dataset ini.
        - Fitur finansial (Keuntungan/Kerugian Kapital) memiliki kontribusi marginal setelah normalisasi outlier.
        - Model ini dapat digunakan untuk identifikasi pekerja dengan potensi gaji tinggi untuk program pengembangan karir atau retensi.
        """)


    # ==================== TAB 5: DOKUMENTASI ====================
    with tabs[4]:
        st.header("Dokumentasi Proyek")
        
        st.subheader("1. Penjelasan Dataset")
        st.markdown("""
        Dataset yang digunakan dalam proyek ini diadaptasi dari **UCI Adult Census Income Dataset** (Kohavi, 1996) 
        yang memuat profil sosio-demografis dan pekerjaan individu untuk memprediksi tingkat pendapatan. 
        Dataset mentah (`train.csv`) memiliki total baris **35.994 baris** dan **13 kolom** (fitur).
        
        **Distribusi Target:**
        - **Kelas ≤7jt (Gaji Rendah)**: 27.364 baris (~76%)
        - **Kelas >7jt (Gaji Tinggi)**: 8.630 baris (~24%)
        - **Rasio Imbalance**: Sekitar 3.17:1, menunjukkan ketidakseimbangan kelas yang signifikan.
        """)
        
        # Column description table
        doc_cols = pd.DataFrame([
            {"Nama Fitur": "id", "Tipe": "Numerik", "Deskripsi": "Indeks / Nomor Urut data (Dihapus dari Pemodelan)"},
            {"Nama Fitur": "Umur", "Tipe": "Numerik", "Deskripsi": "Usia Pekerja (di-clipping dalam batas IQR [-1 - 79] tahun)"},
            {"Nama Fitur": "Kelas Pekerja", "Tipe": "Kategorik", "Deskripsi": "Sektor ketenagakerjaan (Wiraswasta, Pekerja Negara, dll.)"},
            {"Nama Fitur": "Pendidikan", "Tipe": "Kategorik (Ordinal)", "Deskripsi": "Tingkat pendidikan tertinggi (SD hingga Doktor)"},
            {"Nama Fitur": "Jmlh Tahun Pendidikan", "Tipe": "Numerik", "Deskripsi": "Lama durasi menempuh pendidikan dalam tahun"},
            {"Nama Fitur": "Status Perkawinan", "Tipe": "Kategorik", "Deskripsi": "Status perkawinan pekerja (Menikah, Belum Menikah, Cerai, dll.)"},
            {"Nama Fitur": "Pekerjaan", "Tipe": "Kategorik", "Deskripsi": "Sektor pekerjaan spesifik pekerja (Manajerial, Spesialis, dll.)"},
            {"Nama Fituk": "Jenis Kelamin", "Tipe": "Kategorik", "Deskripsi": "Jenis kelamin pekerja (Laki-laki, Perempuan)"},
            {"Nama Fitur": "Keuntungan Kapital", "Tipe": "Numerik", "Deskripsi": "Keuntungan dari investasi keuangan (di-clipping IQR ke [0.0 - 0.0])"},
            {"Nama Fitur": "Kerugian Capital", "Tipe": "Numerik", "Deskripsi": "Kerugian dari investasi keuangan (di-clipping IQR ke [0.0 - 0.0])"},
            {"Nama Fitur": "Jam per Minggu", "Tipe": "Numerik", "Deskripsi": "Jumlah jam kerja per minggu (di-clipping IQR ke [26.0 - 58.0] jam)"},
            {"Nama Fitur": "Gaji (Target)", "Tipe": "Kategorik", "Deskripsi": "Kategori Gaji Pekerja (<=7jt atau >7jt)"}
        ])
        st.table(doc_cols)
        
        st.subheader("2. Ringkasan Metodologi")
        st.markdown("""
        - **Preprocessing Pipeline**:
          - **Pembersihan**: Menghapus kolom `id` dan `Berat Akhir` karena tidak relevan secara prediktif. Mengganti nilai string '?' menjadi NaN pada kolom `Kelas Pekerja` dan `Pekerjaan`. Menghapus duplikasi baris.
          - **Handling Missing Values**: Nilai hilang diimputasi menggunakan metode *Mode* (nilai tersering/`most_frequent`) menggunakan `SimpleImputer` di dalam pipeline.
          - **Handling Outlier**: Digunakan metode *IQR Clipping* dengan batas $[Q1 - 1.5 \\times IQR, Q3 + 1.5 \\times IQR]$ pada kolom numerik (`Umur`, `Keuntungan Kapital`, `Kerugian Capital`, `Jam per Minggu`) untuk membatasi rentang nilai ekstrim tanpa membuang baris data.
          - **Encoding**: 
            - *OrdinalEncoder* diterapkan pada kolom `Pendidikan` berdasarkan urutan logis (SD → 1st-4th → ... → Sarjana → Master → Doktor).
            - *OneHotEncoder* dengan parameter `handle_unknown='ignore'` diterapkan pada variabel nominal.
          - **Scaling**: Standardisasi data menggunakan `StandardScaler` untuk menyamakan skala fitur-fitur numerik.
        
        - **Algoritma Permodelan (5 Model Komparatif)**:
          1. **RF Baseline**: RandomForestClassifier dengan n_estimators=100, random_state=42 (baseline standar)
          2. **RF Weighted**: RandomForestClassifier dengan class_weight='balanced' untuk mengatasi imbalance
          3. **RF Tuned (Model Utama)**: Hasil RandomizedSearchCV dengan 8 iterasi, scoring='f1', 3-fold StratifiedKFold CV
             - Grid search: n_estimators ∈ [100,150,200], max_depth ∈ [10,15,20,None], min_samples_leaf ∈ [1,5,10], min_samples_split ∈ [2,10], max_features ∈ ['sqrt','log2']
          4. **Logistic Regression**: LogisticRegression dengan class_weight='balanced', max_iter=1000
          5. **XGBoost**: XGBClassifier dengan scale_pos_weight (ratio kelas), n_estimators=200, max_depth=6, learning_rate=0.1
        
        - **Mengatasi Imbalance Class**:
          - Karena proporsi kelas target tidak seimbang (~24% berpenghasilan >7jt), semua model dikonfigurasi dengan strategi penanganan imbalance:
            - Random Forest menggunakan `class_weight='balanced'`
            - Logistic Regression menggunakan `class_weight='balanced'`
            - XGBoost menggunakan `scale_pos_weight` berdasarkan rasio kelas di training data
        
        - **Teknik Interpretasi Model (3 Metode)**:
          1. **Feature Importance (Mean Decrease in Impurity)**: Metrik bawaan Random Forest berdasarkan penurunan impurity dalam tree splits
          2. **Permutation Importance**: Metrik model-agnostic yang mengukur perubahan performa saat fitur di-shuffle (n_repeats=10, scoring='f1')
          3. **SHAP (SHapley Additive exPlanations)**: Teknik game theory yang menunjukkan dampak setiap fitur pada prediksi menggunakan TreeExplainer (subsample 300 baris test set, seed=42)
        """)
        
        st.subheader("3. Metrik Kesuksesan Proyek")
        st.markdown("""
        Proyek ini menetapkan target performa model yang spesifik berdasarkan kebutuhan bisnis:
        
        - **Recall untuk kelas >7jt > 0.75**: Model harus mampu mengidentifikasi setidaknya 75% dari pekerja berpenghasilan tinggi (minimize False Negative)
        - **ROC-AUC > 0.85**: Model harus memiliki discriminative ability yang baik, membedakan kedua kelas dengan akurat di berbagai threshold
        
        Target ini dipilih untuk menyeimbangkan:
        - **Sensitivity** (Recall tinggi): Penting untuk program targeting dan intervensi bisnis yang tepat
        - **Discrimination** (ROC-AUC tinggi): Memastikan model tidak hanya recall tinggi tapi juga presisi yang memadai
        """)
        
        st.subheader("4. Panduan Penggunaan Aplikasi")
        st.markdown("""
        - **Dashboard EDA** (Tab 1): Membantu pengguna memvisualisasikan data mentah, sebaran kategori gaji, dan hubungan antar variabel melalui chart interaktif.
        - **Model Demo** (Tab 2): Memungkinkan pengguna memasukkan profil pekerja (umur, pendidikan, pekerjaan, dll.) untuk melihat prediksi kategori gajinya secara instan menggunakan RF Tuned.
        - **Evaluasi Model** (Tab 3): Berisi perbandingan kinerja lima model (RF Baseline, RF Weighted, RF Tuned, Logistic Regression, XGBoost) serta kurva pembelajaran dan cross-validation untuk memantau model utama.
        - **Interpretasi Hasil** (Tab 4): Membantu analis/pengguna memahami fitur mana yang paling memengaruhi prediksi dengan tiga teknik interpretasi: feature importance, permutation importance, dan SHAP.
        - **Dokumentasi** (Tab 5): Referensi lengkap tentang dataset, metodologi, metrik kesuksesan, dan panduan penggunaan aplikasi.
        """)



if __name__ == "__main__":
    main()
